### ISSUE TITLE
Can no longer pair HUE as of homestart-hue 0.1.25

### ISSUE THREAD

**Issue by mcarlson** [dpjanes/homestar-hue#8]
My native object looks like this:
EventEmitter {
  domain: null,
  _events: {},
  _eventsCount: 0,
  _maxListeners: undefined,
  controlPoint:
   EventEmitter {
     domain: null,
     _events: { device: [Function] },
     _eventsCount: 1,
     _maxListeners: undefined,
     devices:
      { 'a3f24e5b-5035-18bc-9708-170f2973da19': [Object],
        '2f402f80-da50-11e1-9b23-0017881d5b1a': [Circular],
        'upnp-InternetGatewayDevice-1_0-2c303391478b': [Object] },
     ssdp:
      ControlPoint {
        domain: null,
        _events: [Object],
        _eventsCount: 4,
        _maxListeners: undefined,
        server: [Object] },
     eventHandler:
      { responseCount: 1,
        server: [Object],
        serverPort: 58283,
        subscriptions: {} } },
  uuid: '2f402f80-da50-11e1-9b23-0017881d5b1a',
  udn: 'uuid:2f402f80-da50-11e1-9b23-0017881d5b1a',
  forgotten: false,
  last_seen: 1465354250464,
  location: 'http://192.168.0.18:80/description.xml',
  deviceType: 'urn:schemas-upnp-org:device:Basic:1',
  friendlyName: 'Philips hue (192.168.0.18)',
  manufacturer: 'Royal Philips Electronics',
  manufacturerUrl: 'http://www.philips.com',
  modelNumber: '929000226503',
  modelDescription: 'Philips hue Personal Wireless Lighting',
  modelName: 'Philips hue bridge 2012',
  modelUrl: 'http://www.meethue.com',
  softwareVersion: null,
  hardwareVersion: null,
  serialNum: null,
  host: '192.168.0.18',
  port: '80',
  localAddress: '192.168.0.5',
  devices: {},
  services: {},
  is_configured: false }

Also, I think there's a typo. When pressing the Pair button during homestar-config (http://192.168.0.5:9998/uuid/2f402f80-da50-11e1-9b23-0017881d5b1a?action=pair) I get a stack trace:
TypeError: Cannot read property 'modelNumber' of undefined
   at HueLightBridge._pair_device (/Users/maxcarlson/teem/dreemgl/classes/iot/node_modules/homestar-hue/HueLightBridge.js:492:20)
   at HueLightBridge._configure_device (/Users/maxcarlson/teem/dreemgl/classes/iot/node_modules/homestar-hue/HueLightBridge.js:457:21)
   at /Users/maxcarlson/teem/dreemgl/classes/iot/node_modules/homestar-hue/HueLightBridge.js:420:14
   at Layer.handle [as handle_request](/Users/maxcarlson/teem/dreemgl/classes/iot/node_modules/express/lib/router/layer.js:95:5)
   at trim_prefix (/Users/maxcarlson/teem/dreemgl/classes/iot/node_modules/express/lib/router/index.js:312:13)
   at /Users/maxcarlson/teem/dreemgl/classes/iot/node_modules/express/lib/router/index.js:280:7
   at param (/Users/maxcarlson/teem/dreemgl/classes/iot/node_modules/express/lib/router/index.js:349:14)
   at param (/Users/maxcarlson/teem/dreemgl/classes/iot/node_modules/express/lib/router/index.js:365:14)
   at Function.process_params (/Users/maxcarlson/teem/dreemgl/classes/iot/node_modules/express/lib/router/index.js:410:3)
   at next (/Users/maxcarlson/teem/dreemgl/classes/iot/node_modules/express/lib/router/index.js:271:10)

**Comment by mcarlson** [comment]
https://github.com/dpjanes/homestar-hue/pull/9 should fix these issues. I can now pair successfully again!

**Comment by dpjanes** [comment]
Just want to confirm: this is a V1 Hue, but the username parameter no longer works? Because of a firmware update?
